### ISSUE TITLE
Unable to update allowed_ips

### ISSUE THREAD

**Issue by fabuzaid21** [kislerdm/terraform-provider-neon#96]
Hi there,

We're running into a problem with applying an update to the `allowed_ips` state in the `neon_project` resource. `allowed_ips_primary_branch_only` is also failing. When we run `terraform plan`, it correctly detects the current state, but `terraform apply` does not make any changes.

### Terraform Version
1.5.5

### Provider Version
Terraform Cloud

### Affected Resource(s)
- allowed_ips
- allowed_ips_primary_branch_only

**Comment by kislerdm** [comment]
Hey @fabuzaid21! Could you please share which version of the terraform Neon provider did you use and share the following information:

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

For context, I cannot reproduce your issue because I have no clarity on what to reproduce - please follow the template when clicking the button "New Issue".

Thanks!

**Comment by kislerdm** [comment]
@fabuzaid21 hey! Also, please clarify which Neon plan are you using. Note that the allow-list for IP addresses is only available for the Scale plan, see details [here](https://neon.tech/docs/manage/projects#configure-ip-allow).

**Comment by fabuzaid21** [comment]
Hi @kislerdm! Sorry for the delay—I missed your reply.

I'm using the latest version—`0.5.0`. And my team is on the Scale plan

**Comment by fabuzaid21** [comment]
Hi @kislerdm,

I've filled out the issue template below:

### Terraform Configuration Files
I've uploaded a ZIP file to Google Drive with a public link: https://drive.google.com/file/d/1Nloab1fWEZJmAP8vudLLkhw4Eh6a2RD7/view?usp=sharing. The file is encrypted with your GPG key (Key ID: `46C0A987D58548F6`).

### Debug Output
https://gist.github.com/fabuzaid21/32d60a0d4f02b7e06c2561a73cc118a1

### Expected Behavior
The `Restrict IP access to protected branches only` checkbox on the `https://console.neon.tech/app/projects/<project_id>/settings/ip_allow` page should be checked.

### Actual Behavior
The checkbox was not checked.

### Steps to Reproduce
1. Initialize the following environment variables:
    1. `allowed_ips` to be an empty list
    2. `is_production_like` to be `false`
    3. `neo_tax_env` to be `"development"`
1. `terraform plan`
1. `terraform apply`

**Comment by fabuzaid21** [comment]
Thank you, @kislerdm! 🙏🏼
